#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Simple Bot to reply to Telegram messages
# This program is dedicated to the public domain under the CC0 license.
"""
This Bot uses the Updater class to handle the bot.
First, a few handler functions are defined. Then, those functions are passed to
the Dispatcher and registered at their respective places.
Then, the bot is started and runs until we press Ctrl-C on the command line.
Usage:
Basic Echobot example, repeats messages.
Press Ctrl-C on the command line or send a signal to the process to stop the
bot.
"""

import logging
import json
import re
import sys
import os

import telegram
from telegram.ext import (
    Updater,
    CommandHandler,
    MessageHandler,
    RegexHandler,
    Filters,
    CallbackQueryHandler,
    Handler,
    TypeHandler, ConversationHandler)

import track_activity
from db_call import add_user
from utils import new_command, now, ricerca, annulla, stima

#==================GLOBAL VARIABLES==========================================
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    level=logging.DEBUG)
logger = logging.getLogger(__name__)

PORT = int(os.environ.get('PORT', '5000'))




#==================FUNCTIONS==========================================

def get_token_bot(debug):
    if debug:
        id = "490902479"
        token = id + ":AAGz3rv4M2U2dYG7WJDbiWZoAFFsUVn_ZIE"
    else:
        id = "333089594"
        token = id + ":AAFossfi9mGnY648Eb5mv3wKO0NbHedrXq0"
    return token

def get_user(user):
    default_null = "!"
    user = {
        'id': user.id,
        'username': getattr(user, 'username', None),
        'first_name': getattr(user, 'first_name', None),
        'last_name': getattr(user, 'last_name', None),
        'language_code': getattr(user, 'language_code', None),
    }
    return user

def get_bot(bot):
    bot = get_user(bot)
    bot['date'] = now()
    return bot

def get_info(bot, update):
    user = get_user(update.message.from_user)
    user['date'] = update.message.date
    bot_id, sep, actual_token = bot.token.partition(':')
    add_user(user, int(bot_id))
    if re.search("^[.!/]", update.message.text):
        track_activity.command(bot, update)
    elif Filters.all(update.message):
        track_activity.text(bot, update)

def button(bot, update):
    query = update.callback_query
    bot.edit_message_text(text="Selected option: %s" % query.data,
                          chat_id=query.message.chat_id,
                          message_id=query.message.message_id)


def alarm(bot, job):
    """Function to send the alarm message"""
    bot.send_message(job.context, text='Beep!')
    
def set(bot, update, args, job_queue, chat_data):
    """Adds a job to the queue"""
    chat_id = update.message.chat_id
    #print(chat_id)
    try:
      # args[0] should contain the time for the timer in seconds
      due = int(args[0])
      if due < 0:
          update.message.reply_text('Sorry we can not go back to future!')
          return

      # Add job to queue
      job = job_queue.run_once(alarm, due, context=chat_id)
      chat_data['job'] = job

      update.message.reply_text('Timer successfully set!')

    except (IndexError, ValueError):
      update.message.reply_text('Usage: /set <seconds>')
      
def unset(bot, update, chat_data):
    """Removes the job if the user changed their mind"""

    if 'job' not in chat_data:
        update.message.reply_text('You have no active timer')
        return

    job = chat_data['job']
    job.schedule_removal()
    del chat_data['job']

    update.message.reply_text('Timer successfully unset!')

def error(bot, update, error):
    logger.warning('Update "%s" caused error "%s"' % (update, error))

def log_update(bot, update):
    logger.info(update)


#==================MAIN==========================================


def main():
    # Create the EventHandler and pass it your bot's token.
    debug = len(sys.argv) > 1
    
    updater = Updater(get_token_bot(debug))

    # Get the dispatcher to register handlers
    disp = updater.dispatcher

    # Handler to get username and other info
    # disp.add_handler(MessageHandler(Filters.all, get_info), -1)
    #disp.add_handler(CommandHandler("set", set,pass_args=True, pass_job_queue=True,pass_chat_data=True))
    #disp.add_handler(CommandHandler("unset", unset, pass_chat_data=True))

    disp.add_handler(RegexHandler("^[.!/]", new_command))

    coversation=ConversationHandler(
        [RegexHandler("^Lista oggetti necessari per",ricerca)],
        states={
            1 : [MessageHandler(Filters.text, stima)]
        },
        fallbacks=[CommandHandler('Annulla', annulla)]
    )

    disp.add_handler(coversation)


    # on different commands - answer in Telegram
    #disp.add_handler(CallbackQueryHandler(button, pattern="\d"))
    disp.add_handler(CallbackQueryHandler(new_command, pattern="^[/.!]dice"))
    
    # log all errors
    disp.add_handler(TypeHandler(telegram.Update, log_update))
    disp.add_error_handler(error)

    # Start the Bot
    #updater.start_polling()
    updater.start_webhook(listen="0.0.0.0",
                      port=PORT,
                      url_path="main")
    updater.bot.set_webhook("https://fancazzistibot.herokuapp.com/main")

    # Run the bot until you press Ctrl-C or the process receives SIGINT,
    # SIGTERM or SIGABRT. This should be used most of the time, since
    # start_polling() is non-blocking and will stop the bot gracefully.
    updater.idle()


if __name__ == '__main__':
    main()
